name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Show Python version
      run: python -V

    - name: Run the tests
      run: python setup.py test -q

    - name: Install it
      run: python setup.py install

    - name: Install asxxxx
      run: |
        wget -q -U github http://6502.org/tools/asm/asxv5p40_20210426.zip
        unzip -q asxv5p40_20210426.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: sudo apt-get install -y srecord

    - name: Disassemble and reassemble the test program
      run: |
        make -C k0dasm/tests/end_to_end all
